# Generated by Django 2.2.14 on 2020-07-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200709_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='FGGGmjnnnnn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbbbb', models.BigIntegerField()),
            ],
        ),
    ]
